### ISSUE TITLE
Husky/Jackal PID values missing

### ISSUE THREAD

**Issue by shrijan00** [husky/husky#110]
So, I was using husky and Jackal for my application. I was not getting any error until i updated my protobuff in /usr/loca/include/google and gazebo. So now I'm getting this error for both the robot 
![pid](https://user-images.githubusercontent.com/4169231/57454955-4dddeb80-726a-11e9-8caf-a14748cd9485.png)
Anybody has any idea about this? I don't think we need to add specifically PID values. It's just not taking the values from gazebo_ros_control.
If the PID values need to be assigned separately in control.yaml, What should be the values in that case then??

**Comment by civerachb-cpr** [comment]
This is a bug in Gazebo.  See the comments here: https://answers.ros.org/question/293830/what-is-the-fix-for-no-p-gain-specified-for-pid-namespace-gazebo_ros_controlpid_gainsback_right_wheel_joint-ros-melodic/
and here: https://github.com/ros-simulation/gazebo_ros_pkgs/blob/e42cc26a473733b05abc648181a6de1286105ed6/gazebo_ros_control/src/default_robot_hw_sim.cpp#L218

Basically Husky does not use PID values to control the wheels, so we do not specify them in control.yaml.  If you try adding PID values the simulated Husky will not move correctly.  Gazebo is reporting this as an error in its output, even though it's by design that you can omit the PID values in order to force gazebo to use the SetAngle or SetParam(vel) functions.
