### ISSUE TITLE
Husky Laser and PC2  Topic Conflict

### ISSUE THREAD

**Issue by rmerriam** [husky/husky#123]
Ubuntu 18.04
ROS Melodic
Husky Tutorial in simulation with Gazebo

This caused me some confusion so thought I'd mention it here. 

Run the command:
```
roslaunch scout_gazebo scout_playpen.launch kinect_enabled:=true laser_enabled:=true
```
The `/scan` topic reports both the actual laser and the kinect point cloud simulated laser on the topic but with different frames, i.e. base_link and laser_base, and values, i.e. base_link is at lower point on objects. 

Might just need explanation in the tutorial rather than considering it a bug needing a fix in the launch files. The latter would be either disallowing both laser and kinect to be enabled or changing the topic for the kinect simulated laser.  In `spawn_husky.launch` I changed the kinect laser topic.

**Comment by civerachb-cpr** [comment]
Good catch.  With the Kinect being discontinued for some time this is less of an urgency, but we'll look into adding this to our documentation.

**Comment by civerachb-cpr** [comment]
Didn't mean to close this one before. Clicked the wrong button. Sorry!

**Comment by civerachb-cpr** [comment]
Most of the necessary changes should be reflected here: https://github.com/husky/husky/pull/131

The Kinect's "laserscan" should now be on the /kinect/scan topic, instead of /scan.  If you're using the Kinect for the gmapping demo you can specify the scan topic to listen to when launching the demo; it defaults to /scan, but can be overridden.

Because the Kinect has been discontinued I've also added support for the Intel RealSense D400 series as a replacement depth camera.  Mostly the same/similar setup as the kinect (realsense_enabled:=true, laserscan data publishes to /realsense/scan).  There's also support for a physical RealSense in addition to the simulated one added to the husky_bringup package.

**Comment by civerachb-cpr** [comment]
Should be fixed now.
