### ISSUE TITLE
Release for ROS2 or ROS Noetic

### ISSUE THREAD

**Issue by andrestoga** [husky/husky#136]
Hey everyone,

Are there plans for releasing Husky to any version of ROS2 or ROS Noetic? After a quick search I could not find nothing about this.

Thanks!

**Comment by civerachb-cpr** [comment]
We have plans to start working on a Noetic release in the fall/early winter 2020.  I can't give a firm estimate on when that will be released for Husky, since we'll be working on Noetic for all of our major platforms over the course of the next quarter or two.  But we intend to have Noetic support "soon."

As for ROS2, it's being discussed internally, but we haven't made any decisions on a timeline for ROS2 support yet.
