### ISSUE TITLE
Frontier Exploration Demo for Noetic

### ISSUE THREAD

**Issue by Gavriel-CTO** [husky/husky#258]
Can you please explain why it was removed for Melodic and what needs to be done to get it running for Noetic?

**Comment by civerachb-cpr** [comment]
At the time the Husky was upgraded to Melodic, the `frontier_exploration` package was not usable with Melodic.  Rather than delay releasing the Husky update, or releasing it with a broken dependency, we made the decision to remove it completely.

Since that time, there does appear to be a melodic branch of `frontier_exploration` available here: https://github.com/paulbovbel/frontier_exploration/tree/melodic-devel.  I have not tested this branch on Noetic, and don't know if it will work or not.

It appears the package has undergone significant refactoring since the Indigo/Kinetic version.  You're welcome to make use of it, but there's limited support we can offer for getting it to work on a current, Noetic Husky.
