### ISSUE TITLE
Arguments in `teleop.launch` from `husky_control` package

### ISSUE THREAD

**Issue by Tinker-Twins** [husky/husky#259]
@civerachb-cpr, just noticed 3 small issues with the `teleop.launch` file from `husky_control` package:

1. Arguments for both joystick as well as keyboard teleoperation have been set to true simultaneously. https://github.com/husky/husky/blob/741f70882da3abb17578cf594779add985e95b08/husky_control/launch/teleop.launch#L5-L6

2. `teleop_twist_joy` node does not check whether or not the `joystick` argument is true. https://github.com/husky/husky/blob/741f70882da3abb17578cf594779add985e95b08/husky_control/launch/teleop.launch#L21

3. Neither `teleop_twist_joy`, nor `teleop_twist_kb` node shows any output on the screen (which is useful to refer what joystick/keyboard input will correspond to what robot motion). https://github.com/husky/husky/blob/741f70882da3abb17578cf594779add985e95b08/husky_control/launch/teleop.launch#L19-L23

**Comment by civerachb-cpr** [comment]
> Arguments for both joystick as well as keyboard teleoperation have been set to true simultaneously. 

This was intentional so as to allow keyboard or game controller input to be used.  I've just edited the launch file and the twist_mux configuration to make the keyboard teleop use `kb_teleop/cmd_vel` instead of `joy_teleop/cmd_vel`.  The game controller has higher priority and will override the keyboard input.

Because on a normal Husky the teleop.launch file is normally run by the `ros` systemd job, I've set the default for keyboard input to false.  If you want keyboard control you can run
```
roslaunch husky_control teleop.launch joystick:=false keyboard:=true
```
in the foreground (or create an alias/bash script to do this in a shorter command).

Practically-speaking, outside of simulation, there isn't much need to keyboard control of the robot.  All physical Husky robots ship with a game controller.  And if you're using SSH to connect to the robot then rather than using keyboard input you can use the Rviz interactive rings to drive the robot.

> teleop_twist_joy node does not check whether or not the joystick argument is true. 

This is fine.  The latest change I just push will address the possible issues of using the keyboard and game controller simultaneously.

> Neither teleop_twist_joy, nor teleop_twist_kb node shows any output on the screen (which is useful to refer what joystick/keyboard input will correspond to what robot motion). 

The joy nodes have never published any controller button information.  We have separate documentation for all of our robots, and the button layout is defined in the husky_control/config/teleop_* files.

Regarding the keyboard node, the key controls are not configurable, but are well-defined in the documentation for that package.
